# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: controls.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='controls.proto',
  package='radio_box',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x63ontrols.proto\x12\tradio_box\"=\n\x04Play\x12$\n\x04type\x18\x01 \x02(\x0e\x32\x16.radio_box.CommandType\x12\x0f\n\x07station\x18\x02 \x02(\t\",\n\x04Stop\x12$\n\x04type\x18\x01 \x02(\x0e\x32\x16.radio_box.CommandType\"G\n\tSetVolume\x12$\n\x04type\x18\x01 \x02(\x0e\x32\x16.radio_box.CommandType\x12\x14\n\x0cvolume_level\x18\x02 \x02(\r\",\n\x04Quit\x12$\n\x04type\x18\x01 \x02(\x0e\x32\x16.radio_box.CommandType\"\xa7\x01\n\x07\x43ommand\x12\x1f\n\x04play\x18\x01 \x01(\x0b\x32\x0f.radio_box.PlayH\x00\x12\x1f\n\x04stop\x18\x02 \x01(\x0b\x32\x0f.radio_box.StopH\x00\x12*\n\nset_volume\x18\x03 \x01(\x0b\x32\x14.radio_box.SetVolumeH\x00\x12\x1f\n\x04quit\x18\x04 \x01(\x0b\x32\x0f.radio_box.QuitH\x00\x42\r\n\x0bsub_command*;\n\x0b\x43ommandType\x12\x08\n\x04PLAY\x10\x00\x12\x08\n\x04STOP\x10\x01\x12\x0e\n\nSET_VOLUME\x10\x02\x12\x08\n\x04QUIT\x10\x63')
)

_COMMANDTYPE = _descriptor.EnumDescriptor(
  name='CommandType',
  full_name='radio_box.CommandType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PLAY', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STOP', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SET_VOLUME', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='QUIT', index=3, number=99,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=427,
  serialized_end=486,
)
_sym_db.RegisterEnumDescriptor(_COMMANDTYPE)

CommandType = enum_type_wrapper.EnumTypeWrapper(_COMMANDTYPE)
PLAY = 0
STOP = 1
SET_VOLUME = 2
QUIT = 99



_PLAY = _descriptor.Descriptor(
  name='Play',
  full_name='radio_box.Play',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='radio_box.Play.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='station', full_name='radio_box.Play.station', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=90,
)


_STOP = _descriptor.Descriptor(
  name='Stop',
  full_name='radio_box.Stop',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='radio_box.Stop.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=136,
)


_SETVOLUME = _descriptor.Descriptor(
  name='SetVolume',
  full_name='radio_box.SetVolume',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='radio_box.SetVolume.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='volume_level', full_name='radio_box.SetVolume.volume_level', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=209,
)


_QUIT = _descriptor.Descriptor(
  name='Quit',
  full_name='radio_box.Quit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='radio_box.Quit.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=255,
)


_COMMAND = _descriptor.Descriptor(
  name='Command',
  full_name='radio_box.Command',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='play', full_name='radio_box.Command.play', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stop', full_name='radio_box.Command.stop', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='set_volume', full_name='radio_box.Command.set_volume', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quit', full_name='radio_box.Command.quit', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='sub_command', full_name='radio_box.Command.sub_command',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=258,
  serialized_end=425,
)

_PLAY.fields_by_name['type'].enum_type = _COMMANDTYPE
_STOP.fields_by_name['type'].enum_type = _COMMANDTYPE
_SETVOLUME.fields_by_name['type'].enum_type = _COMMANDTYPE
_QUIT.fields_by_name['type'].enum_type = _COMMANDTYPE
_COMMAND.fields_by_name['play'].message_type = _PLAY
_COMMAND.fields_by_name['stop'].message_type = _STOP
_COMMAND.fields_by_name['set_volume'].message_type = _SETVOLUME
_COMMAND.fields_by_name['quit'].message_type = _QUIT
_COMMAND.oneofs_by_name['sub_command'].fields.append(
  _COMMAND.fields_by_name['play'])
_COMMAND.fields_by_name['play'].containing_oneof = _COMMAND.oneofs_by_name['sub_command']
_COMMAND.oneofs_by_name['sub_command'].fields.append(
  _COMMAND.fields_by_name['stop'])
_COMMAND.fields_by_name['stop'].containing_oneof = _COMMAND.oneofs_by_name['sub_command']
_COMMAND.oneofs_by_name['sub_command'].fields.append(
  _COMMAND.fields_by_name['set_volume'])
_COMMAND.fields_by_name['set_volume'].containing_oneof = _COMMAND.oneofs_by_name['sub_command']
_COMMAND.oneofs_by_name['sub_command'].fields.append(
  _COMMAND.fields_by_name['quit'])
_COMMAND.fields_by_name['quit'].containing_oneof = _COMMAND.oneofs_by_name['sub_command']
DESCRIPTOR.message_types_by_name['Play'] = _PLAY
DESCRIPTOR.message_types_by_name['Stop'] = _STOP
DESCRIPTOR.message_types_by_name['SetVolume'] = _SETVOLUME
DESCRIPTOR.message_types_by_name['Quit'] = _QUIT
DESCRIPTOR.message_types_by_name['Command'] = _COMMAND
DESCRIPTOR.enum_types_by_name['CommandType'] = _COMMANDTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Play = _reflection.GeneratedProtocolMessageType('Play', (_message.Message,), dict(
  DESCRIPTOR = _PLAY,
  __module__ = 'controls_pb2'
  # @@protoc_insertion_point(class_scope:radio_box.Play)
  ))
_sym_db.RegisterMessage(Play)

Stop = _reflection.GeneratedProtocolMessageType('Stop', (_message.Message,), dict(
  DESCRIPTOR = _STOP,
  __module__ = 'controls_pb2'
  # @@protoc_insertion_point(class_scope:radio_box.Stop)
  ))
_sym_db.RegisterMessage(Stop)

SetVolume = _reflection.GeneratedProtocolMessageType('SetVolume', (_message.Message,), dict(
  DESCRIPTOR = _SETVOLUME,
  __module__ = 'controls_pb2'
  # @@protoc_insertion_point(class_scope:radio_box.SetVolume)
  ))
_sym_db.RegisterMessage(SetVolume)

Quit = _reflection.GeneratedProtocolMessageType('Quit', (_message.Message,), dict(
  DESCRIPTOR = _QUIT,
  __module__ = 'controls_pb2'
  # @@protoc_insertion_point(class_scope:radio_box.Quit)
  ))
_sym_db.RegisterMessage(Quit)

Command = _reflection.GeneratedProtocolMessageType('Command', (_message.Message,), dict(
  DESCRIPTOR = _COMMAND,
  __module__ = 'controls_pb2'
  # @@protoc_insertion_point(class_scope:radio_box.Command)
  ))
_sym_db.RegisterMessage(Command)


# @@protoc_insertion_point(module_scope)
